name: Automate Changelog
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Git Cliff
        uses: tj-actions/git-cliff@v1.5.0
        id: git-cliff
        with:
          args: "--verbose"
          output: "CHANGELOG.md"
          template-config: https://raw.githubusercontent.com/noclocks/.github/main/workflow-templates/cliff.template.toml
      - name: Print Changelog
        id: print-changelog
        run: |
          cat "CHANGELOG.md"
      - name: Commit and Push
        id: commit-push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "[chore]: update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git "main"
