name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deployment
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.noclocks.dev
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: requirements.txt
